# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Sang-A Ahn's Portfoilo
# Website URL
baseURL: 'https://ansangah.github.io/'
canonifyURLs: false

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  goldmark:
    parser:
      attribute: true    # [링크](...){.btn .btn-primary} 같은 마크다운 클래스 문법 허용
    renderer:
      unsafe: true
sitemap:
  changefreq: weekly
  priority: 0.5
sitemap:
  _merge: deep
icons:
  fontawesome: true
  academicons: true
  lucide: true
header:
  navbar:
    show_search: true