# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageName: "한국어"
  weight: 1            # 가벼울수록(숫자 작을수록) 메뉴 왼쪽/위치상 먼저 옴
  contentDir: "content/ko"
  title: "안상아의 포트폴리오"
  params:
    date_format: "2025-10-11"   # 한국식 날짜 표기
  menu:
    main:
      - name: 홈
        url: '/'
        weight: 1
      - name: 이력서
        url: '/experience/'
        weight: 2
      - name: 소식
        url: '/news/'
        weight: 3
      - name: 프로젝트
        url: '/projects/'
        weight: 4
      - name: 연락하기
        url: '/contact/'
        weight: 5
en:
  languageName: "English"
  weight: 2
  contentDir: "content/en"
  title: "Sang-A Ahn's Portfolio"
  menu:
    main:
      - name: Home
        url: '/'
        weight: 1
      - name: Resumé
        url: '/experience/'
        weight: 2
      - name: News
        url: '/news/'
        weight: 3
      - name: Projects
        url: '/projects/'
        weight: 4
      - name: Contact
        url: '/contact/'
        weight: 5