# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageName: "한국어"
  contentDir: "content/ko"
  title: "안상아의 포트폴리오"
  params:
    date_format: "2025-10-11"   # 한국식 날짜 표기

en:
  languageName: "English"
  contentDir: "content/en"
  title: "Sang-A Ahn's Portfolio"