ko:
  languageName: Korean
  weight: 1
  title: '안상아의 포트폴리오'
  params:
    description: '한국어 사이트 설명'
  menu:
    main:
      - name: 홈
        url: '/'
        weight: 1
      - name: 이력서
        url: '/resume/'
        weight: 2
      - name: 연락하기
        url: '/contact/'
        weight: 3
en:
  languageName: English
  weight: 2
  title: "Sang-a Ahn's Portfolio"
  params:
    description: 'Site description in English'
  menu:
    main:
      - name: Home
        url: '/'
        weight: 1
      - name: Resumé
        url: '/resume/'
        weight: 2
      - name: Contact
        url: '/contact/'
        weight: 3
jp:
  languageName: 日本語
  weight: 3
  title: "アン·サンア | ポートフォリオ"
  params:
    description: 'アン·サンアの経歴、スキル、制作物を紹介するポートフォリオサイトです。'
  menu:
    main:
      - name: ホーム
        url: '/'
        weight: 1
      - name: 履歴書
        url: '/resume/'
        weight: 2
      - name: お問い合わせ
        url: '/contact/'
        weight: 3