# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: '/'
    weight: 10

  - name: 이력
    url: '/experience/'
    weight: 20

  - name: 프로젝트
    url: '/projects/'
    weight: 30

  - name: 블로그
    identifier: blog
    url: '/blog/'
    weight: 40
  - name: 인공지능
    parent: blog
    url: '/blog/ai-blog/'
    weight: 41
  - name: 과목별 정리
    parent: blog
    url: '/blog/subjects/'
    weight: 42
    
  - name: 연락하기
    identifier: contact
    url: '/contact/'
    weight: 50
  - name: 연락처 정보
    parent: contact
    url: '/contact/contact/'
    weight: 51
  - name: 위치 정보
    parent: contact
    url: '/contact/location/'
    weight: 52